### PR TITLE
Add API to list versions

### PR DESCRIPTION
**Pull request by alexarchambault**
Use like
```scala
import scala.concurrent.ExecutionContext.Implicits.global
import coursier._
val availableVersions = Versions()
  .withModule(mod"org.scala-lang:scala-library")
  .versions()
  .unsafeRun()
  .available // Seq[String]
```

### CODE REVIEW

**Comment by fthomas** [comment]
Wow, this looks like it could be used in Scala Steward to find new versions instead of going through sbt and sbt-updates. This has the potential to make Scala Steward a lot faster.

Thanks @alexarchambault!

**Comment by alexarchambault** [comment]
@fthomas But don't you need to start sbt anyway to know about the dependencies themselves (before checking for possible updates)?

**Comment by alexarchambault** [comment]
FYI, I have [a project](https://github.com/alexarchambault/deps/blob/master/WIP-README.md) in the work, that aims to list dependencies outside of sbt itself, like [this](https://github.com/alexarchambault/case-app/blob/deps/deps.json). With those files, it should be possible to e.g. have a single JVM checking for updates for as many projects as necessary. (My goal was to ping you about it as a I'll publicly announce it :)

**Comment by fthomas** [comment]
You're right. Not all invocations of sbt can be eliminated only those that check for updates of all known dependencies.

deps looks cool. Finally a principled way to organize dependencies where it is totally clear where version numbers are defined! It should be easy for Scala Steward to also update `deps.json` files. Even if a project does not use sbt. This is exciting!

**Comment by fthomas** [comment]
@alexarchambault I'm now using Coursier exclusively to find new updates (https://github.com/fthomas/scala-steward/pull/1209) and it is working great so far. Going through all repos now takes 30-40 minutes instead of 5-6 hours. It is so fast now that it had been blacklisted by Maven Central a few times and I had to add a rate limiter to slow it down. :-)

Thanks again for this great addition to Coursier!

**Comment by alexarchambault** [comment]
Thanks for the feedback, @fthomas!

**Comment by fthomas** [comment]
@alexarchambault I was wondering if `Versions` does take [mirrors](https://get-coursier.io/blog/index.html#mirrors) into account? My current understanding of the code is that it does not, but I'm not sure.

I'm still having issues with Maven Central so I tried using a mirror but that didn't help for getting versions. WDYT, should support for mirrors be added to `Versions`?

**Comment by fthomas** [comment]
I added minimal support for mirrors (by copying code from `Resolve`) here and it works for me locally: https://github.com/coursier/coursier/compare/master...fthomas:topic/use-mirrors-in-versions

Should I extend that and also add `mirrorConfFiles` and `mirrors` fields to `Version` so that mirrors can also be set via the API and then open a PR with these changes?

**Comment by fthomas** [comment]
PR for mirrors support: #1515

**Pull request merged**
