### PR TITLE
Add a Task.tailRecM for stack safe loops

### PR DESCRIPTION
**Pull request by johnynek**
this is useful for anyone writing loops with Task (or implementing a cats Monad for Task).

### CODE REVIEW

**Comment by johnynek** [comment]
actually, you are right, the flatMap of Task is stack safe. In general, the Reader flatMap is not stack safe, and your Task is basically `ReaderT[Future, ExecutionContext, A]`. But in the case where the `F[_]` in reader is stack safe, it is okay, as is the case for you.

Indeed, my code would only work in that case, so I think there is no improvement.

**Comment by alexarchambault** [comment]
@johnynek The naive `tailRecM` could be added though, so the test can be kept to ensure `coursier.util.Task` remains stacksafe.

The scalajs jobs on the CI are failing because of the `Await` in the test. But it's not necessary: utest is fine if the test returns a `Future` (it will just look into it, a `countTo(500000).map(n => assert(n == 500000)).future()` should work fine…)

**Comment by johnynek** [comment]
okay, I updated, but it looks like one of the tests flaked.

**Comment by alexarchambault** [comment]
Merging, thanks!

**Pull request merged**
