### PR TITLE
Allow users to add BOMs to resolutions

### PR DESCRIPTION
**Pull request by alexarchambault**
This allows coursier users to pass coordinates of a "BOM" to be used during resolution. The BOM is basically a POM file containing versions (and exclusions too) of dependencies, meant to override versions (and for exclusions, be added) pulled during resolutions.

From the API, users can add BOM coordinates like
```scala
Resolve()
  .addBomDependencies(dep"io.quarkus:quarkus-bom:3.16.2")
// or
Fetch()
  .addBomDependencies(dep"io.quarkus:quarkus-bom:3.16.2")
```

From the CLI, users can use the `--bom` option, like
```text
$ cs resolve --bom io.quarkus:quarkus-bom:3.16.2 org:name:version
```

Both from the API and the CLI, root dependencies can have `_` as a version. In that case, the version is read from the BOM:
```text
$ cs resolve com.google.code.gson:gson:_ --bom io.quarkus:quarkus-bom:3.16.2
```

### CODE REVIEW

**Comment by alexarchambault** [comment]
Includes https://github.com/coursier/coursier/pull/3097 for now

**Comment by tgodzik** [comment]
Btw. @alexarchambault fetching `org.jboss.xnio:xnio-nio:3.8.16.Final` now brings in `jboss-logging-3.4.3` instead of previous `jboss-logging-3.3.1`, might be related to the change but I am not sure if that is expected. Doesn't change anything for metals, but wanted to mention it.

**Comment by tgodzik** [comment]
Context https://github.com/scalameta/metals/pull/6935

**Comment by alexarchambault** [comment]
@tgodzik Thanks for reporting that. The change looks correct. [`org.jboss.xnio:xnio-nio:3.8.16.Final`](https://repo1.maven.org/maven2/org/jboss/xnio/xnio-nio/3.8.16.Final/xnio-nio-3.8.16.Final.pom) has [`org.jboss.xnio:xnio-all:3.8.16.Final`](https://repo1.maven.org/maven2/org/jboss/xnio/xnio-all/3.8.16.Final/xnio-all-3.8.16.Final.pom) as parent, which has `org.jboss.logging:jboss-logging:3.4.3.Final` in its dependency management section. This overrides the `org.jboss.logging:jboss-logging` versions pulled by `org.jboss.xnio:xnio-nio:3.8.16.Final` transitive dependencies, with this PR's changes. So `3.4.3.Final` is the expected version now.

**Comment by tgodzik** [comment]
Thanks for confirming and the context!

**Pull request merged**
