### PR TITLE
Write exclusions and transitiveness in sbt update reports, add sbt-shared module

### PR DESCRIPTION
**Pull request by alexarchambault**
Fixes https://github.com/coursier/coursier/issues/684.

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
From a quick glance this appears to put the FromSbt and ToSbt classes into a separate module, so my librarymanagement PR can use them.

Am I seeing this correctly?

**Comment by alexarchambault** [comment]
@leonardehrenfried Yep, these are in the `sbt-shared` module now. To depend on it, something like
```scala
addSbtPlugin("io.get-coursier" % "sbt-shared" % "1.0.0-RC14")
```
should do.

**Comment by dwijnand** [comment]
I think we should add anything that coursier needs and that is currently missing in https://github.com/dwijnand/sbt-compat, rather than have competing skim library..

@leonardehrenfried Do you think you could take that on?

**Comment by alexarchambault** [comment]
@dwijnand That would be cool, indeed.

**Comment by leonardehrenfried** [comment]
Maybe I don't get it, but as far as I see sbt-compat is for backporting APIs from 1.0 to 0.13.

What the new module is providing is conversions from coursier to sbt and vice versa.

**Comment by dwijnand** [comment]
You're right, ToSbt and FromSbt are for that. But there's also a bunch of code (in scala-2.10 and scala-2.12) to handle sbt 1 vs sbt 0.13. That code should migrate to sbt-compat (imho).

**Comment by leonardehrenfried** [comment]
Ah, I see. Yes I can make a PR for that.

**Comment by leonardehrenfried** [comment]
@dwijnand I've made a PR at https://github.com/dwijnand/sbt-compat/pull/5. Would you be able to take a look?

**Comment by dwijnand** [comment]
Sorry @leonardehrenfried I've been a bit busy with end of the year wrap ups. But I have that PR on the top of my list for the beginning of the year. :-/

**Pull request merged**
