### PR TITLE
Make coursierLoggerFactory a Task rather than a Setting

### PR DESCRIPTION
**Pull request by teozkr**
Not sure what I was thinking there..

### CODE REVIEW

**Comment by teozkr** [comment]
I ran `sbt scripted` locally, and none of the failures seemed to have anything to do with this change.

**Comment by teozkr** [comment]
I don't like `coursierLogger` since it sounds like it just creates a `Cache.Logger` rather than a `() => Cache.Logger` (arguably it would be good to change that... but that seems like it would require bigger changes).

**Comment by alexarchambault** [comment]
Merging, thanks!

**Comment by alexarchambault** [comment]
Going to cut `1.1.0-M5` later today.

**Pull request merged**
