### PR TITLE
Add Pants build tool

### PR DESCRIPTION
**Pull request by wisechengyi**
Per discussion https://github.com/coursier/coursier/issues/695

The only code change is at https://github.com/coursier/coursier/pull/709/files#diff-7ca3c74b5087813a533febc6b4a5a7a1R9 as coursier.properties is probably auto generated by sbt. Pants does support build properties but not in this fashion.

The commits are from repurposing other branches, but the actual change is purely declarative.

### CODE REVIEW

**Comment by alexarchambault** [comment]
@wisechengyi You shoudn't need to add jackson as a dependency in this PR, do you?

That said, I can merge anyway if you'd like…

**Comment by wisechengyi** [comment]
Ah thanks. Forgot to remove it since I was working backwards. Now removed.

**Comment by alexarchambault** [comment]
Ok, so merging!

(A bit a pity that pants doesn't call its build files `PANTS` though…, like buck calls his, `BUCK`.)

Thanks @wisechengyi !

**Comment by wisechengyi** [comment]
haha. actually there has been conversation about converging pants, bazel, and buck to use a common build language called skylark https://github.com/google/skylark. but no nothing immediate yet.

**Pull request merged**
