### PR TITLE
Upgrade to sbt 1.1.0, update sbt-pack

### PR DESCRIPTION
**Pull request by leonardehrenfried**
Why is it good to upgrade sbt? Because 1.1.0 has support for LSP which in turn lets you use VSCode. (I personally have problems loading the build in IntelliJ - VSCode is better than nothing)

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Hmm, the AppVeyor build fails with 

```
java.io.IOException: CreateFile() failed with error 3
[error] 	at sbt.internal.io.WinMilli$.getHandle(Milli.scala:275)
[error] 	at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:281)
[error] 	at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:259)
[error] 	at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:66)
[error] 	at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:352)
[error] 	at sbt.io.IO$.getModifiedTime(IO.scala:1143)
[error] 	at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1212)
[error] 	at sbt.util.FileInfo$lastModified$.apply(FileInfo.scala:150)
[error] 	at sbt.util.FileInfo$lastModified$.apply(FileInfo.scala:125)
```

The stacktrace makes me think that this could have something to do with the changes to milli-second precision of modified dates introduced in 1.1.0.

Or is this a known issue?

**Comment by alexarchambault** [comment]
Not known on my side…

I relaunched the Appveyor build with a clean cache, with no success.

**Comment by dwijnand** [comment]
Known and already fixed issue: https://github.com/sbt/sbt/issues/3871

It'll be fixed in 1.1.1.

**Comment by leonardehrenfried** [comment]
Alright, I will wait for 1.1.1 and update the PR.

Am 15.01.2018 3:40 nachm. schrieb "Dale Wijnand" <notifications@github.com>:

**Comment by leonardehrenfried** [comment]
I appear to have accidentally deleted my original change. When 1.1.1 is here, I will try again.

**Pull request closed without merging**
