### PR TITLE
Fix Scala version enforcement

### LINKED ISSUE #2054: Transitive dependency suffix gets overwritten by the scala version of current subproject
This was originally reported by @OlegYch as https://github.com/sbt/sbt/issues/6439

## steps

sbt 1.5.0

`build.sbt`
```
lazy val settings = List(
  scalaVersion := "2.13.5",
)
lazy val a = project
  .settings(
    settings,
    libraryDependencies ++= List(
      "org.typelevel" % "macro-compat_2.13.0-RC2" % "1.1.1",
    )
  )

lazy val b = project.dependsOn(a).settings(
  settings,
)
```

## problem

```
sbt:sbt-test101> update
[warn]
[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last b / update for the full output
[error] (b / update) sbt.librarymanagement.ResolveException: Error downloading org.typelevel:macro-compat_2.13.5:1.1.1[error]   Not found
[error]   Not found
[error]   not found: C:\Users\OlegYch\.ivy2\local\org.typelevel\macro-compat_2.13.5\1.1.1\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/typelevel/macro-compat_2.13.5/1.1.1/macro-compat_2.13.5-1.1.1.pom
[error] Total time: 0 s, completed Apr 9, 2021 3:22:06 PM
```
## expectation

dependency is not affected by current scala version

## notes by Eugene

Downgrading lm-coursier-shaded from 2.0.8 to 2.0.7 seems to fix the problem:

```scala
val lmCoursierShaded = "io.get-coursier" %% "lm-coursier-shaded" % "2.0.7"
```

https://github.com/coursier/sbt-coursier/compare/v2.0.7...v2.0.8 This updates underlying Coursier from 2.0.12 to 2.0.15.

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #2054 / https://github.com/sbt/sbt/issues/6439

### Problem
Currently `forceScalaVersionOpt` option, which by default is set to true
when a Scala version is present, conflates the notion of overriding the
Scala standard modules (such as scala-library, scala-reflect) and
overriding the cross building full suffix of any libraries.

This ignores the user's specification of dependency such as
`"org.typelevel" % "macro-compat_2.13.0-RC2" % "1.1.1"`
and substitutes it with `"macro-compat_2.13.5"` etc.

Side note: Maybe this was convenient feature when Typelevel had its own Scala compiler? Today, it's more common to want to use a Scala plugin with different Scala full suffix (for debugging purpose or because plugin is not available yet) than using third-party compiler implementation.

### Solution
Create a new option specifically to override the full suffix, and make it opt-in.
Scala modules should continue to enjoy the Scala version overriding.

### CODE REVIEW

**Review by alexarchambault — APPROVED** [review]
Thanks @eed3si9n, and sorry for the late review :|

I pushed a few more commits to merge with the current master, and make sure the `ResolutionParams` hash computation in tests doesn't change in spite of the additional field.

If the CI is green, and if you're ok with it, I'll probably merge from a different branch after rebasing, and merging the "Clean-up" / "Bintray" / "NIT" commits in yours (unless you want to handle it that yourself?)

**Comment by eed3si9n** [comment]
> If the CI is green, and if you're ok with it, I'll probably merge from a different branch after rebasing, and merging the "Clean-up" / "Bintray" / "NIT" commits in yours

Sounds good to me :)

**Comment by alexarchambault** [comment]
Merged via https://github.com/coursier/coursier/pull/2104.

**Comment by eed3si9n** [comment]
@alexarchambault Could you release a new version of Coursier with this patch please?

**Comment by alexarchambault** [comment]
The release workflow of coursier needs to be fixed… I should have a bit of time for it later this week.

**Pull request closed without merging**
