### PR TITLE
Revitalize Mima setup and switch to mill-mima plugin

### LINKED ISSUE #2878: Mima checks seem to be disabled / ineffective
The build has support for Mima, to detect binary incompatibilities. 

```
> mill resolve __.mimaReportBinaryIssues
[1/1] resolve 
cache.jvm[2.12.18].mimaReportBinaryIssues
cache.jvm[2.13.6].mimaReportBinaryIssues
core.jvm[2.12.18].mimaReportBinaryIssues
core.jvm[2.13.6].mimaReportBinaryIssues
coursier.jvm[2.12.18].mimaReportBinaryIssues
coursier.jvm[2.13.6].mimaReportBinaryIssues
env[2.12.18].mimaReportBinaryIssues
env[2.13.6].mimaReportBinaryIssues
install[2.12.18].mimaReportBinaryIssues
install[2.13.6].mimaReportBinaryIssues
interop.cats.jvm[2.12.18].mimaReportBinaryIssues
interop.cats.jvm[2.13.6].mimaReportBinaryIssues
interop.scalaz.jvm[2.12.18].mimaReportBinaryIssues
interop.scalaz.jvm[2.13.6].mimaReportBinaryIssues
jvm[2.12.18].mimaReportBinaryIssues
jvm[2.13.6].mimaReportBinaryIssues
launcher[2.12.18].mimaReportBinaryIssues
launcher[2.13.6].mimaReportBinaryIssues
sbt-maven-repository.jvm[2.12.18].mimaReportBinaryIssues
sbt-maven-repository.jvm[2.13.6].mimaReportBinaryIssues
util.jvm[2.12.18].mimaReportBinaryIssues
util.jvm[2.13.6].mimaReportBinaryIssues
```

But those checks effectively don't run, as there are no previous versions configured.

```
> mill show __.mimaPreviousArtifacts
[1/1] show 
[
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ],
  [
    
  ]
]
```

### PR DESCRIPTION
**Pull request by lefou**
If I add all stable 2.x releases as versions to which we check compatibility against, we'll see a lot of issues, so apparently, coursier `2.1.x` broke compatibility with `2.0.x`.

I just added all available `2.1.x` releases as baseline. 

Fix #2878

### CODE REVIEW

**Comment by lefou** [comment]
These are the current issues (against `2.1.7`):

```
Scanning binary compatibility in /home/lefou/work/opensource/coursier/out/cache/jvm/2.13.6/compile.dest/classes ...
Found 1 issue when checking against io.get-coursier:coursier-cache_2.13:2.1.7
 * static method directoriesInstance(java.lang.String)coursier.cache.shaded.dirs.ProjectDirectories in class coursier.paths.CoursierPaths has a different result type in current version, where it is dev.dirs.ProjectDirectories rather than coursier.cache.shaded.dirs.ProjectDirectories
   filter with: ProblemFilter.exclude[IncompatibleResultTypeProblem]("coursier.paths.CoursierPaths.directoriesInstance")
[110/1469] cache.jvm[2.13.6].mimaReportBinaryIssues failed
[211/1469] cache.jvm[2.12.18].mimaReportBinaryIssues 
Scanning binary compatibility in /home/lefou/work/opensource/coursier/out/cache/jvm/2.12.18/compile.dest/classes ...
Found 1 issue when checking against io.get-coursier:coursier-cache_2.12:2.1.7
 * static method directoriesInstance(java.lang.String)coursier.cache.shaded.dirs.ProjectDirectories in class coursier.paths.CoursierPaths has a different result type in current version, where it is dev.dirs.ProjectDirectories rather than coursier.cache.shaded.dirs.ProjectDirectories
   filter with: ProblemFilter.exclude[IncompatibleResultTypeProblem]("coursier.paths.CoursierPaths.directoriesInstance")
[211/1469] cache.jvm[2.12.18].mimaReportBinaryIssues failed
```

**Comment by alexarchambault** [comment]
Thanks a lot for doing this, @lefou!

I think the errors you're seeing originate from the check being run on the `compile` task output (or maybe that, packaged as is), rather than the JAR we get once shading is applied (where `dev.dirs` gets renamed to `coursier.cache.shaded.dirs`)

**Comment by lefou** [comment]
@alexarchambault Good point. I wasn't aware that mill-mima isn't using the `jar` but only the `compile` output. So it isn't comparing apples to apples, so to say.

Opened https://github.com/lolgab/mill-mima/pull/142

**Comment by lefou** [comment]
@alexarchambault This is now ready for review.

**Review by alexarchambault — APPROVED** [review]
Looks great, thanks @lefou!

**Pull request merged**
