### PR TITLE
Stuff

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by alexarchambault** [comment]
Allows to run things like
```
$ coursier launch ammonite
$ coursier launch ammonite --typevel
```

That triggers a search for `ammonite` in the Scala Index, to get the corresponding artifacts.

Fixes https://github.com/alexarchambault/coursier/issues/324 (although the implem here is a bit different than what was discussed there).

**Comment by alexarchambault** [comment]
cc @MasseGuillaume

**Comment by MasseGuillaume** [comment]
I'm taking a look ;-).

**Comment by MasseGuillaume** [comment]
This is what I tried so far:
## works:
* [x] ammonite
* [x] [abandon](https://index.scala-lang.org/hrj/abandon) (accounting) (ping @hrj)
* [x] [bfg-repo-cleaner](https://index.scala-lang.org/rtyley/bfg-repo-cleaner) (ping @rtyley)
* [x](laika)(https://index.scala-lang.org/planet42/laika)(ping @planet42)

## does not work:
* [ ] [scalafmt](https://index.scala-lang.org/search?q=scalafmt) (resolves to scalafx)
* [ ] [scalafix](https://index.scala-lang.org/search?q=scalafix) (resolves to scalafx)
* [ ] [coursier](https://index.scala-lang.org/search?q=coursier) (resolvers to softprops/courier) << why not ;-)
* [ ] scalariform resaolves to scurator/scurator
* adam-commands ./coursier launch adam-commands --main com.github.heuermh.adam.commands.ADAMCommandsMain (spark logging not in the classpath)
* dotty (resolvers to scalafix)

Let me hack on https://github.com/scalacenter/scaladex/issues/237 and https://github.com/scalacenter/scaladex/issues/256 durring the weekend before you merge this.

I will add a cli flag so if you identity a project we can map it to a cli artifact. I have to tune the search a bit, for example I'm not sure why dotty resolves to eden, in the web search it's the first hit put not on the api.

I can add a list command to coursier to find all cli projects.

Is it possible to select a different scala version ?
for example: `./coursier launch --scala-version 2.10.6 ammonite` resolves to 2.11.8

**Comment by MasseGuillaume** [comment]
@alexarchambault now scalafix and some other cli projects fails to start because of nailgun.

**Comment by heathermiller** [comment]
OMG! I WANT THIS TO BE REALIZED **SO BADLY**. 💯💯💯💯💯💯💯💯💯

**Comment by MasseGuillaume** [comment]
I added a way to filter by scala version in the api. Is there anything I can do to help ?

**Comment by alexarchambault** [comment]
I'll make a quick pass over the issues, to see the ones I'd like to address before going into an RC cycle for 1.0 (for the core libs mainly, and the launcher for standard artifacts). I'll have another look at this once the RC cycle is put in motion - as this wouldn't be included in the perimeter of what should be stabilized by the RC cycle, extra developments could be made for this.

**Comment by alexarchambault** [comment]
Also, a coursier hackathon should take place in Paris at the end of Feb or before mid-March, organized by the [Paris Scala UG](https://twitter.com/ParisScalaUG) (ping @vil1). Having this work smoothly would make a nice subject for it, if I don't find time for that in the mean time.

**Comment by vil1** [comment]
`s/should/will/` in the comment above :)
If you're interested, I'd suggest to follow @ParisScalaUG on Twitter.

**Comment by alexarchambault** [comment]
*rebased*

**Comment by alexarchambault** [comment]
Rebased again. Made the main class detection a bit more loose, for scalafmt in particular. The following works for me now:
```
$ coursier launch lihaoyi/ammonite # just ammonite pulls https://github.com/alexarchambault/ammonium :-/
$ coursier launch dotty -M dotty.tools.dotc.Main # no main class in the manifest of the jar of dotty
$ coursier launch scalafmt
$ coursier launch alexarchambault/coursier -r https://dl.bintray.com/scalaz/releases # just coursier pulls other stuff
```

Doesn't work
```
$ coursier launch scalafix # launches the scalatest runner :-|
```

**Comment by jvican** [comment]
@MasseGuillaume Is there something missing to merge this?

**Comment by alexarchambault** [comment]
(rebased against latest master)

**Comment by alexarchambault** [comment]
I'd be fine merging this as is for people to be able to start toying with it or using it. I guess most remaining glitches (`ammonite` not corresponding to `lihaoyi/Ammonite`, `coursier` not corresponding to this repo) can be fixed on the scaladex side.

**Comment by jvican** [comment]
I agree with you. Let's see what @MasseGuillaume thinks. If we do merge, we should clearly state this feature is experimental and won't work in some cases.

**Comment by MasseGuillaume** [comment]
Yep we need to make shure scaladex matches the rigth repo. https://github.com/scalacenter/scaladex/issues/389#issuecomment-290072278

**Comment by jvican** [comment]
@MasseGuillaume So if this is done that should be done in SC side, I would suggest we merge this @alexarchambault :smile:.

**Comment by alexarchambault** [comment]
🚀

**Pull request merged**
