### PR TITLE
Automatically checkout handmade metadata git submodule

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by SethTisue** [comment]
trying it: scala/community-builds@3ac80ce24df93f6cbd52e2cd2bec3e29cc17ec06

**Comment by alexarchambault** [comment]
Ah, I forgot to merge that (which should be merged anyway).

@SethTisue Don't hesitate to report back if it fixes the community-build or not.

**Comment by alexarchambault** [comment]
(Keeping the branch for the community build for now…)

**Comment by SethTisue** [comment]
thanks! you can delete the branch now: scala/community-builds@8cb93c0751a6c19d6b81f040db6919d5c8ee3ab9

**Pull request merged**
