### PR TITLE
Set default JVM to adoptium@11

### PR DESCRIPTION
**Pull request by julienrf**

### CODE REVIEW

**Comment by julienrf** [comment]
May fix #2678

**Comment by julienrf** [comment]
The CI is green but I am not sure how well this is covered by the tests :-/ @alexarchambault what do you think?

**Review by tgodzik — APPROVED** [review]
Looks good, but I'm also not sure if there will be any problems caused by this change,

**Review by alexarchambault — APPROVED** [review]
Thanks @julienrf! Merging, but we might as well update to Java 17…

**Pull request merged**
