### PR TITLE
Switch the cli module to scala 2.12 and case-app 2.0.x

### PR DESCRIPTION
**Pull request by alexarchambault**
This PR switches the `cli` module to scala 2.12, and to [case-app](https://github.com/alexarchambault/case-app) 2.0.x.

The switch to the latest case-app allows to split more clearly the options from the actual commands (no more commands in the body of case classes).

This also allows to stop relying on [custom scala-native stuff](https://github.com/coursier/scala-native) to generate scala-native bootstraps. (The custom stuff were required for scala 2.11, that the scala-native tooling wasn't compiled to.)

(This rely on the upcoming milestone of case-app 2.0.0)

### CODE REVIEW

**Comment by wisechengyi** [comment]
looks like nativelib does not support 2.12 yet. https://search.maven.org/#search%7Cga%7C1%7Cnativelib_native0.3

That said I have no problem removing the scala native related code, although we'd like to tried it out given the chance.

**Comment by alexarchambault** [comment]
@wisechengyi There's no problem with scala-native, that's the opposite actually! Here we're roughly relying on the same libraries as the sbt plugin of scala-native, and these are published for scala 2.10 (for their sbt 0.13.x plugin) and scala 2.12 (for sbt 1.x), even though the scala-native program they process are only for scala 2.11 (🙃…)

Previously, I had compiled and published them for scala 2.11 myself, to use them from here (via [this repo](https://github.com/coursier/scala-native)).

**Comment by wisechengyi** [comment]
Oh good to know scala native isn't a blocker. If you can update the patch to make all ci shards but the pants one work, then I can update this branch with the pants portion changes. 

I can see there is a couple of benefits of using 2.12 including smaller binaries and faster build time.

**Comment by alexarchambault** [comment]
@wisechengyi Done, the pants job is the only failing one now.

**Comment by wisechengyi** [comment]
ah thanks. will follow up soon!

**Comment by wisechengyi** [comment]
Hey @alexarchambault found an issue:

resolve went missing.
```
sbt ++2.12.4 "project cli" pack

[tw-mbp-yic coursier_dev (topic/update-cli)]$ cli/target/pack/bin/coursier --help
Coursier 1.0.2-SNAPSHOT
Usage: coursier [options] [command] [command-options]

Available commands: bootstrap, fetch, launch, common, spark-submit

Type  coursier command --help  for help on an individual command
[tw-mbp-yic coursier_dev (topic/update-cli)]$ cli/target/pack/bin/coursier resolve --help
Command not found: resolve
```

**Comment by wisechengyi** [comment]
close and reopen to trigger CI build

**Comment by wisechengyi** [comment]
also CI appears to be flaky

**Comment by alexarchambault** [comment]
It seemed you had reverted the bump to the latest master of [test-metadata](https://github.com/coursier/test-metadata). I think that's what was making the CI fail.

**Comment by wisechengyi** [comment]
Oh..submodules always got me..would you mind reverting the revert (just
went to bed)? I think the Pants changes should work now.

On Feb 7, 2018 1:17 AM, "Alexandre Archambault" <notifications@github.com>
wrote:

It seemed you had reverted the bump to the latest master of test-metadata
<https://github.com/coursier/test-metadata>. I think that's what was making
the CI fail.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/coursier/coursier/pull/748#issuecomment-363705805>, or mute
the thread

**Comment by alexarchambault** [comment]
Now that looks like a - quite sticky - transient error…
```
[error] Server access Error: Received fatal alert: handshake_failure url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-compat/scala_2.10/sbt_0.13/1.2.4/ivys/ivy.xml
[warn] 	module not found: com.dwijnand#sbt-compat;1.2.4
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-compat/scala_2.10/sbt_0.13/1.2.4/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-compat/scala_2.10/sbt_0.13/1.2.4/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /root/.ivy2/local/com.dwijnand/sbt-compat/scala_2.10/sbt_0.13/1.2.4/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.10_0.13/1.2.4/sbt-compat-1.2.4.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /root/.sbt/preloaded/com.dwijnand/sbt-compat/1.2.4/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////root/.sbt/preloaded/com/dwijnand/sbt-compat_2.10_0.13/1.2.4/sbt-compat-1.2.4.pom
```

(ran that job in 3 or 4 times already…)

**Pull request merged**
