### PR TITLE
Test that fails when provided dependency is not in the classpath

### PR DESCRIPTION
**Pull request by 2m**
This issue is a bit related to https://github.com/coursier/coursier/issues/200 but here the issue is that dependencies are resolved successfully however after that the compilation fails.

This test succeeds with the default sbt resolver.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks for the repro. I haven't looked into it in details yet, but I guess it's just an issue with the update report sbt-coursier generates for sbt… It should be an easy fix if that's the case.

**Comment by 2m** [comment]
Spent a bit time here and indeed the difference is in `managedClasspath` value when testing with and without coursier. And the value for the key is derived from the result of `update`: https://github.com/sbt/sbt/blob/ad346f529afec66e606b50ae5b10dfa3686de06f/main/src/main/scala/sbt/Defaults.scala#L1754-L1758

Therefore I should dig further to `update` implementation, but that is quite large. :)

**Comment by alexarchambault** [comment]
@2m I'm not sure how that test can pass... The added dependency, `javax.jms:jms:1.1`, doesn't seem to have a JAR (Central only has a POM for it: https://repo1.maven.org/maven2/javax/jms/jms/1.1/).

And without sbt-coursier, I'm getting
```
[info] Updating ...
[warn]  Detected merged artifact: [FAILED     ] javax.jms#jms;1.1!jms.jar:  (0ms).
[warn] ==== local: tried
[warn]   /home/alexandre/.ivy2/local/javax.jms/jms/1.1/jars/jms.jar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/javax/jms/jms/1.1/jms-1.1.jar
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/alexandre/.sbt/preloaded/javax.jms/jms/1.1/jars/jms.jar
[warn] ==== local-preloaded: tried
[warn]   file:////home/alexandre/.sbt/preloaded/javax/jms/jms/1.1/jms-1.1.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: javax.jms#jms;1.1!jms.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] sbt.librarymanagement.ResolveException: download failed: javax.jms#jms;1.1!jms.jar
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2550)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: download failed: javax.jms#jms;1.1!jms.jar
```
(sbt 1.2.3 - updates run fine with sbt-coursier OTOH).

**Comment by 2m** [comment]
Thank you for looking into this.

Sorry for leaving the resolver with the jar out. The build should have this as well:

```scala
resolvers += ("jboss" at "https://repository.jboss.org/nexus/content/groups/public")
```

And with that I get the following exception when running this particular scripted test:

```
[info] [error] /tmp/sbt_ff7bb938/provided-dependency/Main.scala:1:14: object jms is not a member of package javax
[info] [error] import javax.jms.Message
[info] [error]              ^
[info] [error] /tmp/sbt_ff7bb938/provided-dependency/Main.scala:4:14: not found: type Message
[info] [error]   def p(msg: Message) = println(msg)
[info] [error]              ^
[info] [error] two errors found
[info] [error] (compile:compileIncremental) Compilation failed
[info] [error] Total time: 11 s, completed Oct 2, 2018 8:16:20 AM
[error] x sbt-coursier / provided-dependency
[error]  Cause of test exception: {line 2}  Command failed: compile failed
[error] java.lang.RuntimeException: Failed tests:
[error]         sbt-coursier / provided-dependency
```

P.S.: Somehow I did have `jms.jar` in coursier cache in both:

```
/home/martynas/.coursier/cache/v1/https/repository.jboss.org/nexus/content/groups/public/javax/jms/
/home/martynas/.coursier/cache/v1/https/repo1.maven.org/maven2/javax/jms/
```

I needed to delete those to have this test start failing.

**Comment by alexarchambault** [comment]
I didn't try locally, but something like
```
$ export COURSIER_MODE="update-changing" COURSIER_TTL="0s"
```
ought to make the cache use reproducible. This should make coursier try each repository in order no matter what, even if the second or third repository already has the right artifact in cache.

Then ordering the `resolvers`, with the jboss repository before Central, should have fixed the issue.

But Central isn't defined in `resolvers`, but in `externalResolvers`...

**Comment by 2m** [comment]
I see. I think I got myself confused [by this](https://github.com/coursier/coursier/issues/200#issuecomment-320277132). I thought that comment meant that #200 was fixed. But that comment only meant that the particular issue described [here](https://github.com/coursier/coursier/issues/200#issuecomment-312496716) was fixed.

In that case this ticket is a duplicate of #200.

**Comment by 2m** [comment]
Changing the test case to add the custom resolver at the start of `externalResolvers` and also changing the URL of the resolver from `https` to `http` makes the test-case pass. So I am closing this.

**Pull request closed without merging**
