### PR TITLE
Replace most of SbtCompatibility with sbt-compat

### PR DESCRIPTION
**Pull request by dwijnand**
The sbt-compat version is the latest release from master. I'll cut a stable version if this goes well.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Looks cool!

**Comment by alexarchambault** [comment]
If ever we can't get https://github.com/coursier/coursier/pull/730 to work, the current CI failures could be addressed by ensuring the dependency towards sbt-compat is only added if in scala 2.10 or 2.12.

**Comment by dwijnand** [comment]
I don't things will compile without it, but we can try and see.

**Comment by alexarchambault** [comment]
@dwijnand It should work thanks to https://github.com/coursier/coursier/blob/39c7708297a38d673072835e840a537b2faf2429/project/Settings.scala#L159-L166 😈

**Comment by dwijnand** [comment]
This went green for both checks. So I published sbt-compat 1.2.0 and switched to that.

**Comment by alexarchambault** [comment]
Merging, thanks @dwijnand!

**Pull request merged**
