### PR TITLE
List Support for 0.13.15 in Readme

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
Pretty Simple Readme Edit, but I believe this is already present.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks! sbt `0.13.16-M1` and `1.0.0-M5` are also supported now.

Can you make the edit in `doc/README.md` first? (Then run `sbt tut` to have it reported to the `README.md` at the root.)

**Comment by ChristopherDavenport** [comment]
A little worried that a binary file ended up in there. How would that have happened?

**Comment by alexarchambault** [comment]
Because you (git-)added it? 😉 It's created by a scripted test, but should be [removed by it too](https://github.com/coursier/coursier/blob/7874f62c419f953b0e399ed0df2c3255e8fb1cc9/sbt-coursier/src/sbt-test/sbt-coursier/from/test#L4).

**Comment by ChristopherDavenport** [comment]
I'll reapply, my apologies

**Comment by alexarchambault** [comment]
Looks good. Merging, thanks!

**Pull request merged**
