### PR TITLE
Switch to scala 2.12.5

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by alexarchambault** [comment]
🤔 So on Appveyor, `java -XX:+PrintFlagsFinal -version` says
```
     intx CompilerThreadStackSize                   = 0                                   {pd product}
     intx ThreadStackSize                           = 0                                   {pd product}
     intx VMThreadStackSize                         = 0                                   {pd product}
```

**Comment by alexarchambault** [comment]
@wisechengyi Is there a way to have pants get the scala version from… the environement or the command line? That way, its scala version could be bumped via what was added in https://github.com/coursier/coursier/pull/830 too.

**Comment by wisechengyi** [comment]
@alexarchambault not the current version of pants, but the newer pants has an issue with scalaz/shapeless (https://github.com/pantsbuild/pants/issues/5444), hopefully that can be out of the way soon

**Comment by wisechengyi** [comment]
so #812 would help

**Pull request merged**
