### PR TITLE
Switch build to sbt 1.0.4

### PR DESCRIPTION
**Pull request by alexarchambault**
Blocked by:
- [x] sbt-pack (https://github.com/xerial/sbt-pack/issues/113)
- [x] sbt-proguard (https://github.com/sbt/sbt-proguard/issues/18)
- [x] sbt-sonatype (https://github.com/xerial/sbt-sonatype/pull/46)

### CODE REVIEW

**Comment by xerial** [comment]
Hi. sbt-sonatype 2.0 is ready for sbt-1.0.
I'm also working on migrating sbt-pack for sbt 1.0, but found that some dependent sbt plugins are not supporting sbt-1.0 yet, so migration may take a few days (or a week) to find a workaround.

Thanks

**Comment by xerial** [comment]
Just released sbt-pack 0.9.0 that supports both sbt-0.13 and 1.0.0-RC3.

Now you need to use `enablePlugins(PackPlugin)` instead of adding `packSettings`. See also for the details https://github.com/xerial/sbt-pack#usage

**Comment by alexarchambault** [comment]
@xerial Thanks a lot!

**Comment by wsxarcher** [comment]
sbt-pgp 1.1.0 and sbt-proguard 0.3.0 are out!

**Comment by alexarchambault** [comment]
@wsxarcher Thanks!

There are a few issues with the build now...

**Comment by alexarchambault** [comment]
It seems `sbt ++2.12.1 http-server/publishLocal` doesn't do anything. Tweaking things around [this line](https://github.com/coursier/coursier/blob/ddc0ef74b50907a554d717e88a3f6d0b28a41a04/project/Publish.scala#L24) doesn't seem to change anything.

**Pull request merged**
