### PR TITLE
Allow pom-only snapshot dependencies to be found

### PR DESCRIPTION
**Pull request by rfkm**
Fix for #169 

The change was suggested by @chikei in #169.
While this looks a bit hacky and I'm not also sure whether this will cause any regression, I confirmed this works for my issue.

### CODE REVIEW

**Comment by alexarchambault** [comment]
That doesn't seem to work for me, I'm still getting the errors of https://github.com/coursier/coursier/issues/169 when running
```
$ coursier fetch org.jitsi:jitsi-videobridge:1.0-SNAPSHOT -r https://github.com/jitsi/jitsi-maven-repository/raw/master/releases/ -r https://github.com/jitsi/jitsi-maven-repository/raw/master/snapshots
```

You can test with this branch by running `sbt ++2.11.11 cli/pack` from its sources, then running coursier via `cli/target/pack/bin/coursier`.

**Comment by rfkm** [comment]
Ah, then, my issue might be different from the original problem raised in #169. I confirmed it works with our in-house project. Let me check what is the actual problem.

**Comment by rfkm** [comment]
@alexarchambault 
OK, I confirmed #169 is fixed with a9a8a02. 
Now `coursier fetch` should be able to resolve `org.jitsi:jitsi-videobridge:1.0-SNAPSHOT`, but it seems to be necessary to add ` -r https://jitpack.io`.

**Comment by alexarchambault** [comment]
Thanks a lot for that PR!

I was initially under the idea that https://github.com/coursier/coursier/issues/169 was requiring more work, but it turned out I was wrong.

I'm about to rework a bit how the tests handle things from actual repositories... Currently, things are downloaded from Central (and some other repositories) during the tests. I'll probably create a separate github repo with the things from Central et al., so that these don't have to be downloaded. Then, what's used to resolve `org.jitsi:jitsi-videobridge:1.0-SNAPSHOT` could be added there too, so that non-reg tests can be added for it.

I'll merge this PR after that.

**Comment by rfkm** [comment]
Sounds good! I'm looking forward to the next release :-)

**Comment by alexarchambault** [comment]
This is included in https://github.com/coursier/coursier/pull/581 (merged). Thanks again!

**Pull request closed without merging**
