### PR TITLE
Update directories-jvm to version 23

### LINKED ISSUE #1913: Running project with sbt 1.4.2 on Windows 10 - Couldn't find pwsh.exe
Hi,

Getting this error, when running a sbt project on Windows 10 with sbt version 1.4.2:

```
java.lang.RuntimeException: Couldn't find pwsh.exe or powershell.exe on path or in default system locations
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.Util.windowsFallback(Util.java:265)
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.Util.getWinDirs(Util.java:163)
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.ProjectDirectories.fromPath(ProjectDirectories.java:254)
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.ProjectDirectories.from(ProjectDirectories.java:308)
        at lmcoursier.internal.shaded.coursier.paths.CoursierPaths.coursierDirectories(CoursierPaths.java:90)
        at lmcoursier.internal.shaded.coursier.paths.CoursierPaths.computeCacheDirectory(CoursierPaths.java:53)
        at lmcoursier.internal.shaded.coursier.paths.CoursierPaths.computeCacheDirectory(CoursierPaths.java:37)
        at lmcoursier.internal.shaded.coursier.paths.CoursierPaths.cacheDirectory(CoursierPaths.java:66)
        at lmcoursier.internal.shaded.coursier.paths.CachePath.defaultCacheDirectory(CachePath.java:97)
        at lmcoursier.internal.shaded.coursier.cache.CacheDefaults$.location$lzycompute(CacheDefaults.scala:16)
        at lmcoursier.internal.shaded.coursier.cache.CacheDefaults$.location(CacheDefaults.scala:16)
        at lmcoursier.CoursierDependencyResolution$.defaultCacheLocation(CoursierDependencyResolution.scala:275)
        at sbt.coursierint.LMCoursier$.defaultCacheLocation(LMCoursier.scala:44)
        at sbt.Defaults$.$anonfun$buildLevelIvySettings$1(Defaults.scala:508)
        at scala.Function1.$anonfun$compose$1(Function1.scala:49)
        at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
        at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
        at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
        at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
        at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: no output from process
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.Util.runCommands(Util.java:201)
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.Util.runWinCommands(Util.java:226)
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.Util.windowsFallback(Util.java:263)
        ... 22 more
```

Powershell is in PATH and it also works with versions of sbt <= 1.3.13

Someone else getting this errors?

### PR DESCRIPTION
**Pull request by fthomas**
This updates the `modules/directories` submodule to directories-jvm version 23 which hopefully fixes #1913. More info about the changes in this version are in https://github.com/dirs-dev/directories-jvm/issues/43.

### CODE REVIEW

**Review by alexarchambault — APPROVED** [review]
Thanks @fthomas!

**Comment by alexarchambault** [comment]
FYI, I'll cut a release as soon as https://github.com/coursier/coursier/pull/1928 is merged (waiting for the CI to pass).

**Comment by fthomas** [comment]
Thanks @alexarchambault! I'll then bump the Coursier version in sbt.

**Comment by eed3si9n** [comment]
We would need https://github.com/coursier/sbt-coursier after Coursier proper becomes available to Maven Central.

**Pull request merged**
