### PR TITLE
Switch to scala 2.12.9

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by eatkins** [comment]
Would this have the potential to evict 2.12.8 in sbt? I ask because we ran into some issues with 2.12.9 in sbt and we want sbt to stay on 2.12.8: https://github.com/sbt/sbt/issues/4935.

**Comment by alexarchambault** [comment]
Yeah, good point. I won't merge then.

**Comment by eatkins** [comment]
Thanks!

**Comment by alexarchambault** [comment]
Superseded by https://github.com/coursier/coursier/pull/1381.

**Pull request closed without merging**
