### PR TITLE
Resolution perf improvments

### PR DESCRIPTION
**Pull request by jtjeferreira**
optimization from this flamegraph

image

### CODE REVIEW

**Comment by jtjeferreira** [comment]
hi @alexarchambault,

I think `Resolution` performance can also be improved by tweaking `Dependency`, hashcode and equals. I tried to change code to use collections of `Resolution.ModuleVersion` instead of `Dependency`, but I broke a lot of tests and gave up. Do you have any hint?

**Comment by alexarchambault** [comment]
Thanks! I'll try to benchmark those changes later on (https://github.com/coursier/coursier/pull/1677#issuecomment-617808229). Don't hesitate to give your own numbers if you have some.

**Comment by alexarchambault** [comment]
> I think Resolution performance can also be improved by tweaking Dependency, hashcode and equals. I tried to change code to use collections of Resolution.ModuleVersion instead of Dependency, but I broke a lot of tests and gave up. Do you have any hint?

Don't hesitate push your attempt on a branch somewhere, so that I can have a look.

**Comment by jtjeferreira** [comment]
already included in #1694

**Pull request closed without merging**
