### PR TITLE
Update coursier native launcher installation documentation

### PR DESCRIPTION
**Pull request by eloots**
- MacOS and Linux instructions to install the native launcher
  are now unified

### CODE REVIEW

**Comment by eloots** [comment]
@alexarchambault 
Maybe the `cs` native launcher installation instructions could be further modified:

- Install `cs` following the instructions that are already in the doc.
- Use `./cs install cs` to install `cs`.
- Remove the local `cs` executable.

WDYT?

**Comment by alexarchambault** [comment]
It'd be nice to have those instructions too, yes. Maybe right after something like "if you wish to put `cs` in your `PATH`, you can do the following: …". And we can also mention that this allows to later update the launcher with `cs update cs`.

**Comment by eloots** [comment]
> It'd be nice to have those instructions too, yes.

@alexarchambault Just updated the instructions along the lines of what you suggested.

**Review by alexarchambault — APPROVED** [review]
Thanks @eloots!

**Pull request merged**
