### PR TITLE
Add optional SCM info.

### LINKED ISSUE #1288: SCM info is missing in definitions
I am working on https://github.com/fthomas/scala-steward/issues/82 to include a link to the upgraded project in the Scala Steward's PR.
I am using `coursier` to extract URLs of dependencies .

IIUC, `coursier` extracts `homePage` from `pom.xml`, but does not extract [SCM infos](https://maven.apache.org/scm/maven-scm-plugin/usage.html) currently.
https://github.com/coursier/coursier/blob/39d54c266db155a55eef11e2c1bac409d4ef1c1e/modules/core/shared/src/main/scala/coursier/core/Definitions.scala#L255-L261

`homePage` may be enough, but I think SCM info (URL to repository) is more useful, since it may use `Releases` pages that contain release note.

If adding SCM infos is acceptable, I am happy to open a PR.

### PR DESCRIPTION
**Pull request by exoego**
Closes #1288

### CODE REVIEW

**Comment by exoego** [comment]
Looks like tests passed but mima checker failed due to new field in `Info` case class.
What should I do to resolve?

**Comment by exoego** [comment]
Added mima filter and all mima error gone.
Only webasite job faillure, which seems I could not handle 🤔 
https://travis-ci.org/coursier/coursier/jobs/563406500#L965

**Comment by alexarchambault** [comment]
Merging, thanks @exoego!

**Comment by fthomas** [comment]
@exoego I've noticed that `scm` is `None` when `developerConnection` is missing in the POM. But not setting `developerConnection` seems to be common:
```
    <scm>
        <url>https://github.com/typelevel/cats-effect</url>
        <connection>git@github.com:typelevel/cats-effect.git</connection>
    </scm>
```

**Comment by exoego** [comment]
I will submit a PR to coursier

**Comment by fthomas** [comment]
Thanks! It seems that according to the [XSD](http://maven.apache.org/xsd/maven-4.0.0.xsd) all elements in `<scm>` are optional.

**Comment by exoego** [comment]
Opened a PR in https://github.com/coursier/coursier/pull/1331

**Pull request merged**
