### PR TITLE
Trim whitespaces around version specifiers

### LINKED ISSUE #408: Whitespace in version not handled
Whitespace in a version of a transitive dependency is not handled correctly.  For example, the following dependency:

`libraryDependencies += "org.jboss.resteasy" % "resteasy-jaxrs" % "3.0.19.Final"`

Results in the following error

> 
> [info] Resolved coursier-bug-whitespace dependenciesmmons-parent/28/commons-parent-28.pom
> [trace] Stack trace suppressed: run last *:coursierResolution for the full output.
> [error] (*:coursierResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
> [error]   org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.0_spec:1.0.0.Final
> [error]         :
> [error]     not found:
> [error]       /Users/broberts/.ivy2/local/org.jboss.spec.javax.ws.rs/jboss-jaxrs-api_2.0_spec/1.0.0.Final
> [error]         /ivys/ivy.xml
> [error]       https://repo1.maven.org/maven2/org/jboss/spec/javax/ws/rs/jboss-jaxrs-api_2.0_spec/1.0.0.Final%0A%20%20%20%20%20%20%20%20/jboss-jaxrs-api_2.0_spec-1.0.0.Final%0A%20%20%20%20%20%20%20%20.pom
> [error] Total time: 3 s, completed Dec 8, 2016 8:42:23 AM

Minimal project showing bug: https://github.com/flicken/coursier-bug-whitespace

### PR DESCRIPTION
**Pull request by kzys**
Fixes #408.

----

I'm not sure Fetch is the best place to fix this issue though.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks! I was thinking about doing the trimming right after parsing POMs (and possibly user-supplied versions from the CLI too).

**Comment by kzys** [comment]
For this particular issue, the spaces are coming from http://central.maven.org/maven2/org/jboss/resteasy/resteasy-jaxrs-all/3.0.19.Final/resteasy-jaxrs-all-3.0.19.Final.pom's properties section that doesn't have semantics which allows us to trim spaces.

Maybe we should trim spaces after expanding the properties in versions.

**Comment by kzys** [comment]
So, like this?
https://github.com/kzys/coursier/commit/bb3774ef70e4aab4783e111f9cb27b5eca36aa4f

Will update the tests this week.

**Comment by kzys** [comment]
Updated the PR by moving the trimming from Fetch to Resolution, where properties are expanded in a version string.

**Comment by kzys** [comment]
Hmm, I don't think the failure was caused by this change.

**Comment by alexarchambault** [comment]
All property values seem to be actually trimmed by Maven (discussed [here](http://stackoverflow.com/questions/7389995/how-do-i-preserve-whitespace-in-a-maven-plugin-configuration) or [there](https://issues.apache.org/jira/browse/MNG-5380)). These could be trimmed right after having been parsed, in https://github.com/alexarchambault/coursier/blob/master/core/shared/src/main/scala/coursier/maven/Pom.scala.

(Sorry to answer this a bit late, I took a few days off my Github projects recently, I'm back now :-)

**Comment by alexarchambault** [comment]
@kzys I'm fine with merging this as is, and trim all properties later.

**Comment by alexarchambault** [comment]
It would be nice to have an explicit test for `org.jboss.resteasy:resteasy-jaxrs:3.0.19.Final` too, as in https://github.com/alexarchambault/coursier/issues/408.

**Comment by kzys** [comment]
Let me update the PR this weekend or early next week.

**Comment by kzys** [comment]
Rebased against master to make this PR fast forward-able

**Comment by alexarchambault** [comment]
Ah, looks like I missed that this branch was updated. Merging, thanks!

**Comment by alexarchambault** [comment]
(Re-running the failing Travis CI build just in case before merging.)

**Pull request merged**
