### PR TITLE
refactor: remove dollar sign for easier copy paste

### LINKED ISSUE #2901: docs: `$` makes copying and pasting less convenient

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #2901.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks!

Let me quickly check what it looks like locally (tomorrow, Europe time), then I'll merge.

**Comment by hamirmahal** [comment]
@alexarchambault wanted to follow up because it's been a few months :grimacing:

**Review by alexarchambault — APPROVED** [review]
Merging, thanks!

**Comment by hamirmahal** [comment]
You're welcome!

**Pull request merged**
