### PR TITLE
Use latest Ubuntu 22.04 LTS for building aarch64 binaries

### PR DESCRIPTION
**Pull request by mkurz**

### CODE REVIEW

**Comment by mkurz** [comment]
I somehow try to solve #2636, so I guess using the latest Ubuntu is probably a good idea, to use a newer gcc and other toolkits.

**Comment by tgodzik** [comment]
> I somehow try to solve #2636, so I guess using the latest Ubuntu is probably a good idea, to use a newer gcc and other toolkits.

Although it seems that it might break for anyone using an earlier ubuntu :thinking:

**Comment by mkurz** [comment]
> Although it seems that it might break for anyone using an earlier ubuntu :thinking:

Why do you think so?

**Comment by mkurz** [comment]
@tgodzik Can you once more approve the workflows? As you can see I uncommented a condition so the arm64 binaries gets uploaded as artifacts. I would like to download them and try and see if it works for me on my machine. Thanks!

**Comment by tgodzik** [comment]
> > Although it seems that it might break for anyone using an earlier ubuntu thinking
> 
> Why do you think so?

I had that issue since newer gcc was not available for ubuntu 20.04

**Comment by mkurz** [comment]
One workflow fails because jitpack is down... https://github.com/jitpack/jitpack.io/issues/5337
So we need to wait until it comes back up.

**Comment by mkurz** [comment]
@tgodzik So because jitpack is down, I temporary removed the test workflow, so we are not blocked here any more.
Could you once more approve the workflows? Thanks!

**Comment by mkurz** [comment]
Nevermind, I set up my own repo to test the workflows.

**Comment by mkurz** [comment]
Using Ubuntu 22.04 does not really help, I still get an error:
```
Fatal error: Failed to create the main Isolate. (code 9)
```
This time however it's code 9, not code 8 (whatever that means...)

**Pull request closed without merging**
