### PR TITLE
Update, extract & override scala versions for plugins

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Hmm, why does this change cause the Scala 2.11.11 build to fail on this test? 

```
X coursier.IvyXmlTests.no truncation 11ms 
  java.lang.NoClassDefFoundError: scala/Product$class
    coursier.core.Info.<init>(Definitions.scala:119)
    coursier.core.Info$.<init>(Definitions.scala:134)
    coursier.core.Info$.<clinit>(Definitions.scala:-1)
    coursier.package$.<init>(package.scala:46)
    coursier.package$.<clinit>(package.scala:-1)
    coursier.IvyXmlTests$.$anonfun$tests$2(IvyXmlTests.scala:10)
  java.lang.ClassNotFoundException: scala.Product$class
    java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    coursier.core.Info.<init>(Definitions.scala:119)
    coursier.core.Info$.<init>(Definitions.scala:134)
    coursier.core.Info$.<clinit>(Definitions.scala:-1)
    coursier.package$.<init>(package.scala:46)
    coursier.package$.<clinit>(package.scala:-1)
    coursier.IvyXmlTests$.$anonfun$tests$2(IvyXmlTests.scala:10)
Tests: 1, Passed: 0, Failed: 1
[info] 
[error] Failed tests:
[error] 	coursier.IvyXmlTests
[error] (sbt-coursier/test:test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by alexarchambault** [comment]
Yep, `sbt ++2.11.12 sbt-coursier/test` now fails.

I'm not too fond of the way the former sbt-doge handles things. It makes `sbt ++2.11.12 …` compile a few things… in 2.12…

**Comment by dwijnand** [comment]
Given there is no sbt for Scala 2.11 how can you even compile sbt-coursier?

**Comment by alexarchambault** [comment]
I don't want to, but I still expect `sbt ++2.11.12 compile` or `sbt ++2.11.12 test` to work fine (simply not compiling / testing anything for sbt-based projects).

**Comment by alexarchambault** [comment]
Ideally, the sbt-doge based stuff should just trap the projects with no matching scala versions in their `crossScalaVersions`, rather than e.g. compiling them in 2.12 when users do a `sbt ++2.11.12 …`

**Comment by dwijnand** [comment]
That's exactly what should be happening.. I'll see what's going on in CI.

**Comment by dwijnand** [comment]
@alexarchambault Do you know how I can reproduce the issue? From the build log it looks like it failed when running `sbt ++2.11.11 jvm/test jvm/it:test`. I can't get that to fail, and I also tried a bunch of variations:

```
++2.11.11 sbt-coursier/testOnly coursier.IvyXmlTests
++2.11.11 'sbt-coursier/testOnly coursier.IvyXmlTests'
sbt-coursier/testOnly coursier.IvyXmlTests
sbt-coursier/testOnly *IvyXmlTests
sbt-coursier/test
```

There must be something about the build I'm not getting.

**Comment by alexarchambault** [comment]
On https://github.com/coursier/coursier/pull/730/commits/2bb13384ad65406181dc04440bb0c70924947cfb, both `sbt ++2.11.11 jvm/test` and `sbt ++2.11.11 sbt-coursier/test` fail on my machine.

**Comment by dwijnand** [comment]
Yep that fails for me too.

I think I was confused with `+`. If you run `+jvm/test` or `+sbt-coursier/test` I think it should skip running `sbt-coursier/test` with 2.11.

The reason I wrote these changes is so I could use `+sbt-plugins/compile` while iterating on https://github.com/coursier/coursier/pull/731. That's now merged. So I'll try and recover something that works here so it can be merged.

**Comment by dwijnand** [comment]
Green (on Travis CI)!

**Comment by alexarchambault** [comment]
Cool that this works!

**Comment by alexarchambault** [comment]
Ah ok, it doesn't set `crossScalaVersions` for the individual sbt plugin projects…

**Comment by alexarchambault** [comment]
Merging, thanks!

**Comment by dwijnand** [comment]
Yeah, so `+blah` on the individual plugins might fail, but on `sbt-plugins` it'll still work, because `sbt-plugins` isn't aggregated on by `jvm`.

**Pull request merged**
