### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SRGOM**
Elaborate a bit on the most common use case.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks. The first added paragraph mentions that coursier uses the ivy cache though, which is not the case. A few things will land in the ivy cache when sbt starts, to get sbt-coursier in particular. Once sbt-coursier is loaded, it will handle dependencies, possibly downloading in its own cache things already downloaded by sbt/ivy.

**Comment by SRGOM** [comment]
@alexarchambault I got the impression that coursier checked in my ivy cache for the presence of a jar before downloading but I may have been wrong.. Let me check again.

**Comment by SRGOM** [comment]
@alexarchambault My first paragraph means something different- it says- Coursier "downloads" from ivy cache into coursier cache. Does it not? I get the following error if I turn the internet off- 

```
[error]   com.timushev.sbt:sbt-updates;sbtVersion=0.13;scalaVersion=2.10:0.3.0:
[error]     download error:
[error]       Caught java.net.UnknownHostException: repo1.maven.org (repo1.maven.org)
[error]       Caught java.net.UnknownHostException: repo.scala-sbt.org (repo.scala-sbt.org)
[error]       Caught java.net.UnknownHostException: oss.sonatype.org (oss.sonatype.org)
[error]       Caught java.net.UnknownHostException: oss.sonatype.org (oss.sonatype.org)
[error]       Caught java.net.UnknownHostException: oss.sonatype.org (oss.sonatype.org)
[error]       Caught java.net.UnknownHostException: repo.typesafe.com (repo.typesafe.com)
[error]       Caught java.net.UnknownHostException: repo.typesafe.com (repo.typesafe.com)
[error]       Caught java.net.UnknownHostException: repo.typesafe.com (repo.typesafe.com)
[error]       Caught java.net.UnknownHostException: repo.typesafe.com (repo.typesafe.com)
[error]       Caught java.net.UnknownHostException: jcenter.bintray.com (jcenter.bintray.com)
[error]     not found: /home/srgom/.ivy2/local/com.timushev.sbt/sbt-updates/scala_2.10/sbt_0.13/0.3.0/ivys/ivy.xml

```

which seems to imply that there was a search into ~/.ivy2/local (although my cache is in ~/.ivy2/cache actually so my statement is probably not true)

**Comment by alexarchambault** [comment]
Two more things :-)
- can you rebase on the latest master, and first do the changes to `doc/README.md`, then run `sbt tut` for those to be reported to the `README.md` at the root?
- I'm not too happy with the first paragraph... coursier doesn't handle the very first dependency fetchings of sbt (that fetch sbt itself and the first plugins, sbt-coursier being one of them).

**Comment by alexarchambault** [comment]
Closing this for now. Might cherry-pick the second paragraph later (or re-open with just it if you'd like).

**Pull request closed without merging**
